### ISSUE TITLE
Wrong margin between gamepad areas

### ISSUE THREAD

**Issue by Dinir** [Dinir/mini-padder#22]
**Describe the bug**
It was meant to be 8px but was not properly set with the right attributes.

**Expected behavior**
It should be set with the right attributes to be 8px.

**Browser** 
OBS 27.2.4

- - -

This is a temporary patch I made for myself, and I never got time to properly apply these changes into the stylesheets.
Rather than keeping it by myself, I decided to share it until I get time to make a proper commit one day.

Paste this css into OBS Browser's Custom CSS. I was going to change the margin to 4px, so this css will set it to 4px.
```css
#canvas-container[data-width='2'] > div:nth-child(2n-1) {margin-right: 4px;}
#canvas-container[data-width='2'] > div:nth-child(2n) {margin-right: -1px;}
#canvas-container[data-width='3'] > div {margin-right: 4px;}
#canvas-container[data-width='3'] > div:nth-child(2) {margin-right: 3px;}
#canvas-container[data-width='3'] > div:last-child {margin-right: -1px;}
```
