### ISSUE TITLE
add an option to stack all the gamepad areas

### ISSUE THREAD

**Issue by Dinir** [Dinir/mini-padder#23]
Having DS4Windows may make gamepad inputs shown via multiple logical gamepads. I could stack some skins together to catch all the inputs that are coming from one physical gamepad, and here's the Custom CSS I used to achieve that.
```css
/* stack everything, show first layer of xinput */
#canvas-container > div { position: absolute; }
#canvas-container > div[data-id="XInput"] > canvas { display: none; }
#canvas-container > div[data-id="XInput"] > canvas:first-child { display: unset; }
```
I can't have time to work on Mini Padder, so I am just pasting this css here instead.
It does exactly what the comment says. It's probably not practical to use this css as it is in general.
